# Generated by Django 2.1.2 on 2018-11-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace_typy_zivnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmena_typu', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace_zivnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_zivnosti', models.CharField(max_length=120)),
                ('typ_zivnosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Rezervace_typy_zivnosti')),
            ],
        ),
        migrations.CreateModel(
            name='Zivnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jazyk_zivnosti', models.CharField(max_length=3)),
                ('jmeno_zivnosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Rezervace_zivnosti')),
            ],
        ),
    ]
