# Generated by Django 2.1.2 on 2019-01-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('business_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.BusinessCategories')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Business')),
                ('login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True)),
                ('open_from', models.TimeField(blank=True, null=True)),
                ('closed_at', models.TimeField(blank=True, null=True)),
                ('pause_starts', models.TimeField(blank=True, null=True)),
                ('pause_finish', models.TimeField(blank=True, null=True)),
                ('is_open', models.CharField(default='T', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notes.Settings'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.BusinessCategories'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.BusinessTypes'),
        ),
        migrations.AlterUniqueTogether(
            name='openhours',
            unique_together={('day', 'company')},
        ),
    ]
