# Generated by Django 2.1.2 on 2018-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervace_typy_zivnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmena_typu', models.CharField(max_length=120)),
                ('jazyk_zivnosti', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervace_zivnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_zivnosti', models.CharField(max_length=120)),
                ('jazyk_zivnosti', models.CharField(max_length=3)),
                ('typ_zivnosti', models.IntegerField()),
            ],
        ),
    ]
